@startuml
left to right direction
scale 1.8
title Diagramme de cas d'utilisation - Chefchaouen Bleu Durable

actor "Visiteur" as Visiteur
actor "Administrateur" as Admin
actor "Editeur" as Editeur

Admin <|-- Editeur

rectangle "Blog : Chefchaouen - Bleu Durable" {
  (Consulter la page d'acceuil) as UC1
  (Consulter la liste des articles) as UC2
  (Voir les détails d'un article) as UC3
  (Rechercher / filtrer un article) as UC4
  (Commenter) as UC5
  (Liker / Sauvegarder un article) as UC6
  (Partager un article) as UC7
  (Créer les articles) as UC8
  (Valider les articles) as UC9
}

' Relations du Visiteur
Visiteur -- UC1
Visiteur -- UC2
Visiteur -- UC3
Visiteur -- UC4
Visiteur -- UC5
Visiteur -- UC6
Visiteur -- UC7

' Relations de l'Editeur
Editeur -- UC8

' Relations de l'Administrateur
Admin -- UC9

@enduml
